from __future__ import annotations

import re
from collections.abc import Sequence
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from trialmatchai.interop.models import ClinicalFact, PatientProfile
from trialmatchai.interop.narrative import render_patient_narrative
from trialmatchai.matching.retrieval.synonyms import disease_synonyms
from trialmatchai.utils.logging_config import setup_logging
from trialmatchai.utils.text import flatten_text

logger = setup_logging(__name__)


FirstLevelChannelKind = Literal[
    "primary_condition",
    "other_condition",
    "concept_synonym",
    "broader_disease",
    "narrative",
    "biomarker",
    "therapy",
]

DEFAULT_CHANNEL_WEIGHTS: dict[FirstLevelChannelKind, float] = {
    "primary_condition": 1.0,
    # 0.25 (not 0.5): keeps comorbidity hits in the tail rather than evicting relevant main-condition
    # trials under the max_trials_first_level cap. Swept empirically -- Pareto win over 0.5.
    "other_condition": 0.25,
    "concept_synonym": 0.9,
    "narrative": 0.8,
    "biomarker": 0.7,
    "therapy": 0.45,
    "broader_disease": 0.35,
}

# One focused channel per comorbidity: a blended query over many conditions dilutes BM25 and the
# mean query vector to near-noise (~1/5 recall). Cap the count to bound latency; list is importance-ordered.
_MAX_OTHER_CONDITION_CHANNELS = 25


class FirstLevelQueryChannel(BaseModel):
    kind: FirstLevelChannelKind
    terms: list[str]
    weight: float = Field(ge=0.0)
    source: str = "deterministic"

    model_config = ConfigDict(extra="forbid")


class FirstLevelQueryPlan(BaseModel):
    patient_id: str | None = None
    channels: list[FirstLevelQueryChannel] = Field(default_factory=list)
    filters: dict[str, Any] = Field(default_factory=dict)

    model_config = ConfigDict(extra="forbid")

    def terms_for(self, *kinds: FirstLevelChannelKind) -> list[str]:
        allowed = set(kinds)
        return dedupe_terms(
            term
            for channel in self.channels
            if channel.kind in allowed
            for term in channel.terms
        )


class FirstLevelCandidateEvidence(BaseModel):
    nct_id: str
    score: float
    channels: list[dict[str, Any]] = Field(default_factory=list)

    model_config = ConfigDict(extra="forbid")


class FirstLevelQueryPlanner:
    def __init__(self, *, entity_annotator: Any = None) -> None:
        self.entity_annotator = entity_annotator

    def build(
        self,
        *,
        profile: PatientProfile,
        matching_summary: dict[str, Any],
        config: dict[str, Any] | None = None,
        age: int | str | None = None,
        sex: str | None = None,
        overall_status: str | None = None,
    ) -> FirstLevelQueryPlan:
        cfg = config or {}
        channels: list[FirstLevelQueryChannel] = []
        primary_terms = dedupe_terms(
            [
                *matching_summary.get("main_conditions", []),
                *positive_fact_labels(profile.conditions),
            ]
        )
        channels.append(
            self._channel("primary_condition", primary_terms, "matching_summary")
        )

        # One focused channel per comorbidity (see _MAX_OTHER_CONDITION_CHANNELS); drop terms
        # already in the primary channel to avoid redundancy.
        other_condition_terms = [
            term
            for term in dedupe_terms(matching_summary.get("other_conditions", []))
            if term.casefold() not in {p.casefold() for p in primary_terms}
        ]
        for term in other_condition_terms[:_MAX_OTHER_CONDITION_CHANNELS]:
            channels.append(self._channel("other_condition", [term], "matching_summary"))

        synonym_terms = self._synonym_terms(primary_terms)
        channels.append(self._channel("concept_synonym", synonym_terms, "concept_linker"))

        # Prefer the broader categories the expansion step generated; fall back to the
        # hand-coded ontology rollups when expansion is off or returned none.
        #
        # These used to come from a SECOND llm pass (the llm_expansion channel, weight 0.5).
        # Measured over sampled TREC 2023 patients, 82% of that pass's terms were already in
        # keywords.json -- it read the enriched summary and handed the same aliases back, so
        # it re-searched what primary_condition (1.0) and other_condition (0.25) already
        # covered. Broader categories were the ONLY thing it contributed, so they are
        # generated by the one expansion call instead and routed here at 0.35. Searching a
        # broad category at 1.0 alongside the specific diagnosis would flood the pool.
        summary_broader = dedupe_terms(
            [
                str(term)
                for term in (matching_summary.get("broader_conditions") or [])
                if str(term).strip()
            ]
        )
        broader_terms = summary_broader or broader_disease_terms(
            [*primary_terms, *synonym_terms]
        )
        channels.append(
            self._channel(
                "broader_disease",
                broader_terms,
                "query_expansion" if summary_broader else "deterministic",
            )
        )

        narrative_terms = narrative_terms_from_summary_or_profile(
            profile,
            matching_summary,
        )
        channels.append(self._channel("narrative", narrative_terms, "patient_narrative"))

        biomarker_terms = dedupe_terms(
            [
                *positive_fact_labels(profile.genomic_findings),
                *biomarker_terms_from_facts(profile.cancer_profile),
            ]
        )
        channels.append(self._channel("biomarker", biomarker_terms, "patient_profile"))

        therapy_terms = therapy_terms_from_profile(profile)
        channels.append(self._channel("therapy", therapy_terms, "patient_profile"))

        return FirstLevelQueryPlan(
            patient_id=profile.patient_id,
            channels=[channel for channel in channels if channel.terms],
            filters={
                "age": age,
                "sex": sex,
                "overall_status": overall_status,
                "hard_filters": cfg.get(
                    "hard_filters",
                    ["age", "sex", "overall_status"],
                ),
            },
        )

    def _channel(
        self,
        kind: FirstLevelChannelKind,
        terms: Sequence[str],
        source: str,
    ) -> FirstLevelQueryChannel:
        return FirstLevelQueryChannel(
            kind=kind,
            terms=dedupe_terms(terms),
            weight=DEFAULT_CHANNEL_WEIGHTS[kind],
            source=source,
        )

    def _synonym_terms(self, primary_terms: Sequence[str]) -> list[str]:
        output: list[str] = []
        for term in primary_terms[:5]:
            output.extend(disease_synonyms(self.entity_annotator, term))
        return dedupe_terms(output)

def fuse_first_level_channel_hits(
    channel_hits: Sequence[tuple[FirstLevelQueryChannel, list[dict], list[float]]],
    *,
    size: int,
    rrf_k: int = 60,
) -> tuple[list[dict], list[float], list[FirstLevelCandidateEvidence]]:
    candidates: dict[str, dict[str, Any]] = {}
    evidence: dict[str, list[dict[str, Any]]] = {}
    for channel, trials, scores in channel_hits:
        for rank, (trial, raw_score) in enumerate(zip(trials, scores), start=1):
            nct_id = str(trial.get("nct_id") or "")
            if not nct_id:
                continue
            contribution = channel.weight / (rrf_k + rank)
            if nct_id not in candidates:
                candidates[nct_id] = {
                    "trial": trial,
                    "score": 0.0,
                }
                evidence[nct_id] = []
            candidates[nct_id]["score"] += contribution
            evidence[nct_id].append(
                {
                    "channel": channel.kind,
                    "rank": rank,
                    "raw_score": float(raw_score),
                    "weight": channel.weight,
                    "terms": channel.terms,
                    "contribution": contribution,
                }
            )

    ranked = sorted(
        candidates.values(),
        key=lambda item: item["score"],
        reverse=True,
    )[:size]
    trials = [item["trial"] for item in ranked]
    scores = [float(item["score"]) for item in ranked]
    candidate_evidence = [
        FirstLevelCandidateEvidence(
            nct_id=str(item["trial"].get("nct_id")),
            score=float(item["score"]),
            channels=evidence.get(str(item["trial"].get("nct_id")), []),
        )
        for item in ranked
    ]
    return trials, scores, candidate_evidence


def positive_fact_labels(facts: Sequence[ClinicalFact]) -> list[str]:
    return dedupe_terms(fact.label for fact in facts if not fact.negated)


def narrative_terms_from_summary_or_profile(
    profile: PatientProfile,
    matching_summary: dict[str, Any],
    *,
    max_chars: int = 1500,
) -> list[str]:
    sentences = matching_summary.get("patient_narrative") or render_patient_narrative(
        profile
    )
    sentences = [
        sentence
        for sentence in sentences
        if " absent" not in str(sentence).casefold()
    ]
    narrative = flatten_text(sentences)
    if not narrative:
        return []
    return [narrative[:max_chars].rsplit(" ", 1)[0].strip() or narrative[:max_chars]]


def biomarker_terms_from_facts(facts: Sequence[ClinicalFact]) -> list[str]:
    terms: list[str] = []
    gene_pattern = re.compile(
        r"\b(ALK|BRAF|BRCA1|BRCA2|EGFR|ERBB2|HER2|KRAS|NTRK|PD-L1|PIK3CA|ROS1|TP53)\b",
        re.IGNORECASE,
    )
    for fact in facts:
        if fact.negated:
            continue
        text = flatten_text([fact.label, fact.description, fact.evidence_text])
        terms.extend(match.group(1).upper() for match in gene_pattern.finditer(text))
    return dedupe_terms(terms)


def therapy_terms_from_profile(profile: PatientProfile) -> list[str]:
    terms: list[str] = []
    for fact in [*profile.medications, *profile.procedures]:
        if fact.negated:
            continue
        terms.append(fact.label)
        if fact.temporality and "prior" in fact.temporality.casefold():
            terms.append(f"prior {fact.label}")
    return dedupe_terms(terms)


def broader_disease_terms(terms: Sequence[str]) -> list[str]:
    output: list[str] = []
    for term in terms:
        normalized = term.casefold()
        if any(
            marker in normalized
            for marker in (
                "cancer",
                "carcinoma",
                "melanoma",
                "sarcoma",
                "tumor",
                "tumour",
                "neoplasm",
            )
        ):
            output.extend(["cancer", "malignant neoplasm", "solid tumor"])
        if any(marker in normalized for marker in ("leukemia", "lymphoma", "myeloma")):
            output.extend(["hematologic malignancy", "blood cancer"])
        if "lung" in normalized and any(
            marker in normalized for marker in ("cancer", "carcinoma", "nsclc")
        ):
            output.extend(["thoracic cancer", "solid tumor"])
    return dedupe_terms(output)


def dedupe_terms(values: Any) -> list[str]:
    if values is None:
        return []
    seen: set[str] = set()
    output: list[str] = []
    for value in values:
        cleaned = re.sub(r"\s+", " ", str(value or "")).strip()
        if not cleaned:
            continue
        key = cleaned.casefold()
        if key in seen:
            continue
        seen.add(key)
        output.append(cleaned)
    return output
